[build]
  base = "netlify"
  publish = "dist"
  command = "node build.js"
  ignore = "false"
  environment = { RUBY_VERSION = "2.6.2", NODE_VERSION="14.3" }

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
